### ISSUE TITLE
Module 'core' has no exported member 'Component'

### ISSUE THREAD

**Issue by dalamar66** [cincheo/jsweet-angular2-quickstart#3]
Hi,

Just tried to run the default quickstart and I got the following error messages:

> > angular2-quickstart@1.0.0 start C:\Workspaces\workspaceJSweet\jsweet-angular2-quickstart
> > tsc && concurrently "tsc -w" "lite-server"
> 
> .generated/app/AppComponent.ts(3,29): error TS2305: Module 'core' has no exported member 'Component'.
> .generated/app/AppComponent.ts(3,29): error TS2339: Property 'Component' does not exist on type 'typeof core'.
> .generated/app/AppModule.ts(3,28): error TS2305: Module 'core' has no exported member 'NgModule'.
> .generated/app/AppModule.ts(3,28): error TS2339: Property 'NgModule' does not exist on type 'typeof core'.
> .generated/app/AppModule.ts(5,28): error TS2304: Cannot find name 'platform_browser'.
> .generated/app/AppModule.ts(5,28): error TS2503: Cannot find namespace 'platform_browser'.
> .generated/app/Globals.ts(3,37): error TS2304: Cannot find name 'platform_browser_dynamic'.
> .generated/app/Globals.ts(3,37): error TS2503: Cannot find namespace 'platform_browser_dynamic'.
> 
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v4.2.0
> npm ERR! npm  v4.0.5
> npm ERR! code ELIFECYCLE
> npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
> npm ERR! Exit status 2

I'm using:

node v4.2.0
npm  v4.0.5
tsc 1.0.3
java 1.8.0_111
Any clue?

**Comment by renaudpawlak** [comment]
You can try the new version updated for JSweet 2. It is quite different, but you still need the right node version...
